apiVersion: apps/v1
kind: Deployment
metadata:
  name: fifaapp-frontend
  namespace: fifaapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fifaapp-frontend
  template:
    metadata:
      labels:
        app: fifaapp-frontend
    spec:
      containers:
        - name: frontend
          image: 782818417469.dkr.ecr.us-east-1.amazonaws.com/fifaapp-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config